# Generated by Django 3.0 on 2020-07-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200704_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='puntuation',
        ),
        migrations.CreateModel(
            name='User_puntuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateTimeField(auto_now_add=True)),
                ('puntuation', models.IntegerField()),
                ('evaluated_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated', to='api.Account')),
                ('evaluator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to='api.Account')),
            ],
        ),
    ]
