# Generated by Django 3.0.8 on 2020-07-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200707_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='problem',
            field=models.CharField(max_length=50, null=True, verbose_name='Problema'),
        ),
    ]
