# Generated by Django 3.0.8 on 2020-07-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200707_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='action',
        ),
    ]
