# Generated by Django 3.0.8 on 2020-07-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200709_2017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puntuation',
            unique_together={('evaluated_user_id', 'evaluator_user_id')},
        ),
    ]
